### ISSUE TITLE
build.bat not working properly

### ISSUE THREAD

**Issue by AutomataVM** [Normmatt/Bomberman-Jetters-GBA-Translation#1]
Hi there, I seem to have a problem when running the build.bat file in my computer. I think I followed the instructions correctly: the game is in the rom folder, named as input.gba, the script has some text already translated (and by the looks of it ready for insertion).

When i execute the build.bat this commands are executed properly:

copy rom\input.gba rom\output.gba
armips.exe asm/SmallVWF.asm
armips.exe asm/Cheats.asm
armips.exe asm/DebugMenu.asm
armips.exe asm/graphicsChanges.asm
armips.exe asm/ItemNamesVWF.asm

but, once it gets to execute the atlas files, it seems to get stuck at the parsing phase:

http://imgur.com/tLqdBQe

afterwards, i get this message: "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

Do you have any idea what the problem might be? using atlas -d build.log gives no insight about what might be wrong. Did i forget something?

Cheers

**Comment by Normmatt** [comment]
Try changing the line endings of the script files to windows or unix (I can't remember which one it expects).

**Comment by AutomataVM** [comment]
Tried with:

unix(LF) : same result, atlas.exe stopped working
windows(CR LF): same result, atlas.exe stopped working
mac(CR) : weird enough, i got a response from atlas, though not the one I expected: http://imgur.com/Ev0UeIM in this one, atlas does not stop working.

**Comment by Normmatt** [comment]
Ohh check the table file "/script/bomberman.tbl" has the same line ending... it might be that causing the issue.

**Comment by AutomataVM** [comment]
Got it, changing it all to windows line (the melissa font .tbl too) end solved the issues. Thanks for your help!
